name: CI

on: 
  push:
    paths-ignore:
      - '**/README.md'
      - 'doc/**'

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Set up Python "3.10"
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        pip3 install -r requirements.txt
        #pip3 uninstall cocotb
        git clone https://github.com/catkira/cocotb.git
        cd cocotb
        pip3 install -e .
        sudo apt install -y --no-install-recommends iverilog
        #git clone https://github.com/steveicarus/iverilog.git
        #cd iverilog
        #git reset --hard 3612577b52d1a1e1980610b218c8f2487a7bb0fe
        #./configure
        #make -j20 install

    - name: Compile Verilator        
      run: |
        sudo apt install libfl-dev help2man
        git clone https://github.com/verilator/verilator.git
        cd verilator
        git reset --hard v5.006
        autoconf
        ./configure
        sudo make -j20
        sudo make install

    - name: Verify with Verilator
      run: |
        SIM=verilator pytest -v tests/test_receiver.py
        SIM=verilator pytest -v tests/test_Decimator_to_SSS_detector.py

    - name: Verify with cocotb & icarus
      run: |
        pytest -v --workers=10 tests/test_PSS_correlator.py
        pytest -v --workers=10 tests/test_PSS_correlator_mr.py
        pytest -v --workers=10 tests/test_PSS_correlator_with_peak_detector.py
        pytest -v --workers=10 tests/test_dot_product.py
        pytest -v tests/test_SSS_detector.py
        pytest -v --workers=10 tests/test_Decimator_Correlator_PeakDetector.py
        pytest -v tests/test_Decimator_Correlator_PeakDetector_FFT.py
        pytest -v --workers=10 tests/test_CFO_correction.py
        pytest -v --workers=9 tests/test_CFO_calc.py
        pytest -v --workers=10 tests/test_channel_estimator.py
        pytest -v tests/test_frame_sync.py
        pytest -v tests/test_div.py
        pytest -v tests/test_atan2.py

